type Activity {
  _id: ID!
  name: String
  description: String
  price: Float
}

input ActivityInput {
  name: String
  description: String
  price: Float
}

type DeleteResponse {
  success: Boolean!
  message: String!
}


type Query {
  activity(_id: ID!): Activity
  activities: [Activity]
}

type Mutation {
  createActivity(data: ActivityInput): Activity
  updateActivity(_id: ID!, data: ActivityInput): Activity
  deleteActivity(_id: ID!): Boolean

}
