type Activity {
  id: ID!
  nome: String
  valor: Float
  descricao: String
 
}

input ActivityInput {
  nome: String
  valor: Float
  descricao: String

}


type Query {
  activity(id: ID!): Activity
  activities: [Activity]
}

type Mutation {
  createActivity(data: ActivityInput): Activity

}
