type RDO {
  _id: ID!
  projeto: Float
  diagrama: Float
  local: String
  encarregado: String
  dataDaProducao: String
  encarregadoQuantidade: Int
  motoristaQuantidade: Int
  eletricistaQuantidade: Int
  auxiliarQuantidade: Int
  climaManha: String
  climaTarde: String
  observacoes: String
  
  createdAt: String
  servicos: [SRV]
}

type SRV {
  _id: ID!
  codigo: Float
  descricao: String
  quantidade: Float
}

input RDOInput {
  projeto: Float
  diagrama: Float
  local: String
  encarregado: String
  climaManha: String
  climaTarde: String
  encarregadoQuantidade: Int
  motoristaQuantidade: Int
  eletricistaQuantidade: Int
  auxiliarQuantidade: Int
  observacoes: String
  dataDaProducao: String
  createdAt: String
  servicos: [SRVInput]
}

input SRVInput {
  codigo: Float
  descricao: String
  quantidade: Float
}

type Query {
  getRDOS: [RDO!]!
  getRDO(_id: ID!): RDO!
}

type Mutation {
  createRDO(data: RDOInput): RDO
}
