type User {
  _id: ID!
  email: String
  senha: String
  token: String
  name: String
}

input UserInput {
  email: String
  senha: String
  token: String
  name: String
}

input LoginInput {
  senha: String
  email: String
}

input GetUsersInput {
  name: String
  email: String
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(data: UserInput): User
  loginUser(loginInput: LoginInput): User
  loginFromEmail(loginInput: LoginInput): User
}
