type User {
  id: ID!
  email: String
  senha: String
  token: String
  name: String
}

input UserInput {
  email: String
  senha: String
  token: String
  name: String
}

input LoginInput {
  senha: String
  email: String
}

input GetUsersInput {
  name: String
  email: String
}

type Query {
  user(id: ID!): User
  users: [User]
}

type Mutation {
  createUser(data: UserInput): User
  loginUser(loginInput: LoginInput): User
  loginFromEmail(loginInput: LoginInput): User
  updateUser(id: ID!, data: UserInput): User!

  deleteUser(id: ID!): Boolean
}
