type Contrato {
  id: ID!
  numero: Float!
  fator: Float!
  csd: String!
}

input ContratoInput {
  numero: Float!
  fator: Float!
  csd: String!
}

type Query {
  contratos: [Contrato!]!
  contrato(numero: Float!): Contrato!
}

type Mutation {
  createContrato(data: ContratoInput!): Contrato!
  updateContrato(id: ID!, data: ContratoInput): Contrato!
  deleteContrato(id: ID!): Boolean
}
