type Codigo {
  _id: ID
  codigo: Float
  descricao: String
  umb: String
  preco: Float
  tipo: String
  fator: Float
  ativo: Boolean
}

input CodigoInput {
  codigo: Float
  descricao: String
  umb: String
  preco: Float
  tipo: String
  fator: Float
  ativo: Boolean
}


type Query {
  codigos: [Codigo!]!
  codigo(codigo: Float!): Codigo!
  codigoByDescription(descricao: String!): Codigo!
  codigoByType(tipo: String!): [Codigo]!
}

type Mutation {
  createCodigo(data: CodigoInput!): Codigo!
  updateCodigo(_id: ID!, data: CodigoInput): Codigo!
  deleteCodigo(_id: ID!): Boolean
}
