type Codigo {
  _id: ID
  code: Float
  description: String
  umb: String
  price: Float
  type: String
  factor: Float
  active: Boolean
}

input CodigoInput {
  code: Float
  description: String
  umb: String
  price: Float
  type: String
  factor: Float
  active: Boolean
}

type Query {
  codigos: [Codigo!]!
  codigo(code: Float!): Codigo!
  codigoByDescription(description: String!): Codigo!
  codigoByType(type: String!): [Codigo]!
}

type Mutation {
  createCodigo(data: CodigoInput!): Codigo!
  updateCodigo(_id: ID!, data: CodigoInput): Codigo!
  deleteCodigo(_id: ID!): Boolean
}
