type Colaborador {
  _id: ID!
  nome: String!
  funcao: String!
  matricula: Float
  equipe: Float
}

input ColaboradorInput {
  nome: String
  funcao: String
  matricula: Float
  equipe: Float
}

type Query {
  colaboradores: [Colaborador!]!
  colaborador(nome: Float!): Colaborador!
}

type Mutation {
  createColaborador(data: ColaboradorInput!): Colaborador!
  updateColaborador(_id: ID!, data: ColaboradorInput): Colaborador!
  deleteColaborador(_id: ID!): Boolean
}
