type Material {
  id: ID
  codigo: Int
  descricao: String
  qnt: Int
}

type Srv {
  id: ID
  codigo: Int
  descricao: String
  qntOrcada: Float
}

type Pendencia {
  id: ID
  descricao: String
  createdAt: String
}

type Ponto {
  id: ID
  tipo: String
  status: String
  ref: Int
  material: [Material]
  srv: [Srv]
  pendencias: [Pendencia]
}

type Coord {
  x: String
  y: String
}

type Projeto {
  id: ID!
  projeto: Float!
  diagrama: Float!
  contrato: Float!
  local: String
  cidade: String
  tipo: String
  status: Float
  coord: Coord
  srv: [Srv]!
  pontos: [Ponto]
}

input MaterialInput {
  codigo: Int
  descricao: String
  qnt: Int
}

input SrvInput {
  codigo: Int
  descricao: String
  qntOrcada: Float
}

input PendenciaInput {
  descricao: String
  createdAt: String
}

input PontoInput {
  tipo: String
  status: String
  ref: Int
  material: [MaterialInput]
  srv: [SrvInput]
  pendencias: [PendenciaInput]
}

input CoordInput {
  x: String
  y: String
}

input ProjetoInput {
  projeto: Float!
  diagrama: Float!
  contrato: Float!
  local: String
  cidade: String
  tipo: String
  status: Float
  coord: CoordInput
  srv: [SrvInput]!
  pontos: [PontoInput]
}

type Query {
  getProjetos: [Projeto!]!
  getProjeto(projeto: Float): Projeto!
}

type Mutation {
  createProjeto(projetoInput: ProjetoInput!): Projeto!
  updateProjeto(id: ID!, data: ProjetoInput): Projeto!
  deleteProjeto(id: ID!): Boolean

  updateStatus(id: ID!, status: Float): Projeto!
}
