type Material {
  id: ID
  codigo: Int
  descricao: String
  qnt: Int
}

type RDODigital {
  id: ID
  codigo: Float
  descricao: String
  planejado: Float
}

type Srv {
  id: ID
  codigo: Int
  descricao: String
  qntOrcada: Int
  qntExecutada: Int
}

type Pendencia {
  id: ID
  descricao: String
  createdAt: String
}

type Ponto {
  id: ID
  tipo: String
  status: String
  ref: Int
  material: [Material]
  srv: [Srv]
  pendencias: [Pendencia]
}

type Coord {
  x: String
  y: String
}

type Projeto {
  id: ID!
  projeto: Float
  diagrama: Float
  contrato: Float
  local: String
  cidade: String
  csd: String
  fiscal: String
  tipo: String
  coord: [Coord]
  RDODigital: [RDODigital]
  pontos: [Ponto]
}

input MaterialInput {
  codigo: Int
  descricao: String
  qnt: Int
}

input RDODigitalInput {
  codigo: Float
  descricao: String
  planejado: Float
}

input SrvInput {
  codigo: Int
  descricao: String
  qntOrcada: Int
  qntExecutada: Int
}

input PendenciaInput {
  descricao: String
  createdAt: String
}

input PontoInput {
  tipo: String
  status: String
  ref: Int
  material: [MaterialInput]
  srv: [SrvInput]
  pendencias: [PendenciaInput]
}

input CoordInput {
  x: String
  y: String
}

input ProjetoInput {
  projeto: Float
  diagrama: Float
  contrato: Float
  local: String
  cidade: String
  csd: String
  fiscal: String
  tipo: String
  coord: [CoordInput]
  RDODigital: [RDODigitalInput]
  pontos: [PontoInput]
}

type Query {
  getProjetos: [Projeto!]!
  getProjeto(projeto: Float): Projeto!
}

type Mutation {
  createProjeto(data: ProjetoInput!): Projeto!
  updateProjeto(id: ID!, data: ProjetoInput): Projeto!
  deleteProjeto(id: ID!): Boolean
}
