type Ferramenta {
  _id: ID!
  nome: String
  descricao: String
  matricula: Float
  equipe: Float
}

input FerramentaInput {
  nome: String
  descricao: String
  matricula: Float
  equipe: Float
}

type Query {
  ferramentas: [Ferramenta!]!
  ferramenta(matricula: Float): Ferramenta!
}

type Mutation {
  createFerramenta(data: FerramentaInput!): Ferramenta!
  updateFerramenta(_id: ID!, data: FerramentaInput): Ferramenta!
  deleteFerramenta(_id: ID!): Boolean
}
